name: Generate Python SBOM (flask-cloud-server)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install CycloneDX Python tool
        run: pip install cyclonedx-bom

      - name: Generate CycloneDX SBOM from requirements.txt
        run: cyclonedx-py requirements -i flask-cloud-server/requirements.txt -o flask-cloud-server/sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-python
          path: flask-cloud-server/sbom.json
