name: Generate SBOM for flask-server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install CycloneDX tool
        run: pip install cyclonedx-bom

      - name: Generate CycloneDX SBOM
        run: cyclonedx-py requirements -i flask-cloud-server/requirements.txt -o sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
